import { z } from "zod";

export const contentBlockSchema = z.object({ id: z.string().min(1), type: z.enum(["heading", "paragraph", "formula", "example", "image-placeholder"]), content: z.string().min(1), conceptIds: z.array(z.string()).min(1), order: z.number().int().positive() });
export const quizItemSchema = z.object({ id: z.string().min(1), afterBlockId: z.string().min(1), conceptIds: z.array(z.string()).min(1), question: z.string().min(1), options: z.array(z.string()).min(2).max(4), correctOptionIndex: z.number().int().nonnegative(), explanation: z.string().min(1), misconceptionByOption: z.record(z.string()).optional() }).superRefine((quiz, ctx) => { if (quiz.correctOptionIndex >= quiz.options.length) ctx.addIssue({ code: z.ZodIssueCode.custom, message: "correctOptionIndex must exist in options" }); });
export const chapterSchema = z.object({ id: z.string().min(1), title: z.string().min(1), subject: z.string().min(1), learningObjectives: z.array(z.string()).min(1), blocks: z.array(contentBlockSchema).min(1), quizzes: z.array(quizItemSchema).min(2) });
export const conceptStateSchema = z.object({ conceptId: z.string(), score: z.number().min(0).max(1), incorrectCount: z.number().int().nonnegative(), questionCount: z.number().int().nonnegative(), lastMisconception: z.string().optional() });
export const quizAttemptSchema = z.object({ quizId: z.string(), selectedOptionIndex: z.number().int().nonnegative(), correct: z.boolean(), createdAt: z.string() });
export const studentStateSchema = z.object({ studentId: z.string(), concepts: z.record(conceptStateSchema), recentAttempts: z.array(quizAttemptSchema) });
export const contentPatchSchema = z.object({ id: z.string(), targetBlockId: z.string(), placement: z.literal("after"), contentType: z.enum(["note", "explanation", "example", "practice-question"]), title: z.string(), body: z.string().max(700), conceptIds: z.array(z.string()).min(1), reason: z.string(), createdAt: z.string(), source: z.enum(["ai", "student"]) });
export const chatMessageSchema = z.object({ role: z.enum(["student", "tutor"]), content: z.string(), referencedBlockIds: z.array(z.string()).optional() });
export const tutorResponseSchema = z.object({ answer: z.string(), referencedBlockIds: z.array(z.string()), conceptSignals: z.array(z.object({ conceptId: z.string(), signal: z.enum(["needs-explanation", "understood"]), confidence: z.number().min(0).max(1) })), suggestPersonalization: z.boolean() });
export const personalizationResponseSchema = z.object({ patches: z.array(contentPatchSchema).max(2) });
export const pdfImportResponseSchema = z.object({ chapter: chapterSchema, extractedCharacterCount: z.number().int().positive() });

export type Chapter = z.infer<typeof chapterSchema>; export type ContentBlock = z.infer<typeof contentBlockSchema>; export type QuizItem = z.infer<typeof quizItemSchema>; export type StudentState = z.infer<typeof studentStateSchema>; export type ContentPatch = z.infer<typeof contentPatchSchema>; export type ChatMessage = z.infer<typeof chatMessageSchema>; export type TutorResponse = z.infer<typeof tutorResponseSchema>; export type PersonalizationResponse = z.infer<typeof personalizationResponseSchema>; export type PdfImportResponse = z.infer<typeof pdfImportResponseSchema>;
