"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import type { Chapter, ChatMessage, ContentPatch, PersonalizationResponse, StudentState, TutorResponse } from "@/types/contracts";
import { activePatches } from "@/lib/patch-renderer";
import { exportMarkdown } from "@/lib/export-markdown";
import { defaultStudentState, recordQuestion, recordQuizAnswer, shouldPersonalize } from "@/lib/learning-state";
import { loadLocal, resetLocal, saveLocal } from "@/lib/storage";
import { demoChapter } from "@/data/chapter.sample";

type ApiResult<T> = T & { fallbackUsed?: boolean; error?: string };
async function post<T>(url: string, body: unknown): Promise<ApiResult<T>> { const res = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) throw new Error(data.error ?? "請求失敗"); return data; }

export default function AdaptiveTextbook() {
  const [chapter, setChapter] = useState<Chapter>(demoChapter); const [chat, setChat] = useState<ChatMessage[]>([]); const [state, setState] = useState<StudentState>(defaultStudentState()); const [patches, setPatches] = useState<ContentPatch[]>([]); const [selectedId, setSelectedId] = useState("formula-area"); const [view, setView] = useState<"original" | "personal">("personal"); const [question, setQuestion] = useState(""); const [loadingTutor, setLoadingTutor] = useState(false); const [updating, setUpdating] = useState<string | null>(null); const [notice, setNotice] = useState(""); const [file, setFile] = useState<File | null>(null); const [importing, setImporting] = useState(false); const [preview, setPreview] = useState<Chapter | null>(null); const ready = useRef(false);
  useEffect(() => { const local = loadLocal(); setChapter(local.chapter); setChat(local.chat); setState(local.state); setPatches(local.patches); setSelectedId(local.chapter.blocks.find((b) => b.id === "formula-area")?.id ?? local.chapter.blocks[0].id); ready.current = true; }, []);
  useEffect(() => { if (ready.current) saveLocal({ chapter, chat, state, patches }); }, [chapter, chat, state, patches]);
  const patchMap = useMemo(() => { const map = new Map<string, ContentPatch[]>(); if (view === "personal") for (const patch of activePatches(chapter, patches)) map.set(patch.targetBlockId, [...(map.get(patch.targetBlockId) ?? []), patch]); return map; }, [chapter, patches, view]);
  const selected = chapter.blocks.find((block) => block.id === selectedId) ?? chapter.blocks[0];
  async function askTutor() { if (!question.trim() || !selected) return; const content = question.trim(); setQuestion(""); setChat((old) => [...old, { role: "student", content }]); setLoadingTutor(true); try { const nextState = recordQuestion(state, selected.conceptIds); setState(nextState); const answer = await post<TutorResponse>("/api/tutor", { chapter, currentBlockId: selected.id, question: content, history: chat.slice(-8), studentState: nextState }); setChat((old) => [...old, { role: "tutor", content: answer.answer, referencedBlockIds: answer.referencedBlockIds }]); if (answer.fallbackUsed) setNotice("Demo fallback used：目前使用固定示範回覆。"); } catch (error) { setNotice(error instanceof Error ? error.message : "導師暫時無法回應。"); } finally { setLoadingTutor(false); } }
  async function answerQuiz(quizId: string, option: number) { const quiz = chapter.quizzes.find((item) => item.id === quizId); if (!quiz) return; const nextState = recordQuizAnswer(state, quiz, option); setState(nextState); const correct = option === quiz.correctOptionIndex; setNotice(correct ? "答對了！你的概念分數已提升。" : `還差一點：${quiz.explanation}`); if (!correct && shouldPersonalize(nextState, quiz.conceptIds[0])) { setUpdating(quiz.afterBlockId); try { const result = await post<PersonalizationResponse>("/api/personalize", { chapter, targetBlockId: quiz.afterBlockId, studentState: nextState, trigger: { type: "incorrect-answer", conceptId: quiz.conceptIds[0], misconception: quiz.misconceptionByOption?.[String(option)] } }); setPatches((old) => [...old, ...result.patches]); setView("personal"); setNotice(result.fallbackUsed ? "教材已更新（Demo fallback used）。" : "教材已依你的回答更新。"); } catch (error) { setNotice(error instanceof Error ? error.message : "教材更新失敗。"); } finally { setUpdating(null); } }
  }
  async function importPdf() { if (!file) return; setImporting(true); setNotice(""); try { const form = new FormData(); form.append("file", file); const res = await fetch("/api/import-pdf", { method: "POST", body: form }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setPreview(data.chapter); } catch (error) { setNotice(error instanceof Error ? error.message : "PDF 匯入失敗。"); } finally { setImporting(false); } }
  function confirmImport() { if (!preview) return; setChapter(preview); setChat([]); setState(defaultStudentState()); setPatches([]); setSelectedId(preview.blocks[0].id); setView("personal"); setPreview(null); setNotice("新教材已載入，可以開始學習。"); }
  function download() { const blob = new Blob([exportMarkdown(chapter, patches)], { type: "text/markdown;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${chapter.id}.md`; anchor.click(); URL.revokeObjectURL(url); }
  function reset() { resetLocal(); setChapter(demoChapter); setChat([]); setState(defaultStudentState()); setPatches([]); setSelectedId("formula-area"); setView("personal"); setNotice("已重設為三角形面積示範教材。"); }
  return <main style={{ maxWidth: 1440, margin: "0 auto", padding: "1.25rem" }}>
    <header style={{ display: "flex", justifyContent: "space-between", gap: "1rem", alignItems: "center", flexWrap: "wrap", marginBottom: "1rem" }}><div><h1 style={{ margin: 0 }}>Adaptive Textbook</h1><p className="muted" style={{ margin: ".35rem 0 0" }}>不是在教科書旁放聊天機器人，而是讓教材隨你演化。</p></div><div style={{ display: "flex", gap: ".5rem" }}><button className="button secondary" onClick={download}>匯出 Markdown</button><button className="button secondary" onClick={reset}>重設 Demo</button></div></header>
    {notice && <p role="status" className="panel" style={{ padding: ".7rem 1rem", color: "#315fda" }}>{notice}</p>}
    <section className="panel" style={{ padding: "1rem", marginBottom: "1rem" }}><b>從 PDF 建立教材</b><p className="muted">僅支援可選取文字的 PDF，最多 10 MB、50 頁；原始檔不會保存。</p><div style={{ display: "flex", flexWrap: "wrap", gap: ".5rem", alignItems: "center" }}><input type="file" accept="application/pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><button className="button" disabled={!file || importing} onClick={importPdf}>{importing ? "正在轉換…" : "轉換並預覽"}</button></div></section>
    {preview && <section className="panel" style={{ padding: "1rem", marginBottom: "1rem", borderColor: "#8da7f8" }}><h2 style={{ marginTop: 0 }}>教材預覽：{preview.title}</h2><p>{preview.blocks.length} 個內容區塊、{preview.quizzes.length} 題測驗</p><ul>{preview.learningObjectives.map((item) => <li key={item}>{item}</li>)}</ul><button className="button" onClick={confirmImport}>開始學習這份教材</button><button className="button secondary" style={{ marginLeft: ".5rem" }} onClick={() => setPreview(null)}>取消</button></section>}
    <div style={{ display: "grid", gridTemplateColumns: "minmax(190px, .7fr) minmax(340px, 1.6fr) minmax(270px, 1fr)", gap: "1rem", alignItems: "start" }}>
      <aside className="panel" style={{ padding: "1rem" }}><p className="badge">{chapter.subject}</p><h2>{chapter.title}</h2><b>學習目標</b><ul className="muted">{chapter.learningObjectives.map((item) => <li key={item}>{item}</li>)}</ul><b>目前進度</b><p className="muted">已加入 {patches.length} 則個人化內容</p></aside>
      <section className="panel" style={{ padding: "1rem" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: ".5rem" }}><h2 style={{ marginTop: 0 }}>教科書</h2><div><button className={`button ${view === "original" ? "" : "secondary"}`} onClick={() => setView("original")}>原始版</button><button className={`button ${view === "personal" ? "" : "secondary"}`} style={{ marginLeft: ".35rem" }} onClick={() => setView("personal")}>我的教材</button></div></div>
        {chapter.blocks.slice().sort((a, b) => a.order - b.order).map((block) => <div key={block.id}><article tabIndex={0} onClick={() => setSelectedId(block.id)} className={`block ${block.id === selectedId ? "selected" : ""} ${block.type === "formula" ? "formula" : ""}`}><span className="muted">{block.id === selectedId ? "目前選取" : "點選以詢問"}</span>{block.type === "heading" ? <h3>{block.content}</h3> : <p>{block.content}</p>}</article>{(patchMap.get(block.id) ?? []).map((patch) => <article className="patch" key={patch.id}><span className="badge">AI 為你加入</span><b style={{ display: "block", marginTop: ".35rem" }}>{patch.title}</b><p>{patch.body}</p></article>)}{updating === block.id && <p className="muted">正在更新你的教材…</p>}{chapter.quizzes.filter((quiz) => quiz.afterBlockId === block.id).map((quiz) => <Quiz key={quiz.id} quiz={quiz} onAnswer={answerQuiz} />)}</div>)}
        {patches.length > 0 && <button className="button secondary" onClick={() => setPatches((old) => old.slice(0, -1))}>復原最新 AI 補充</button>}</section>
      <aside className="panel" style={{ padding: "1rem" }}><h2 style={{ marginTop: 0 }}>AI 導師</h2><p className="muted">目前段落：{selected?.content}</p><div style={{ maxHeight: 390, overflowY: "auto" }}>{chat.length === 0 && <p className="muted">選取一段內容後，問我任何問題。</p>}{chat.map((message, index) => <div key={index} style={{ margin: ".65rem 0", padding: ".65rem", borderRadius: 8, background: message.role === "student" ? "#eaf0ff" : "#f6f8fc" }}><b>{message.role === "student" ? "你" : "導師"}</b><p style={{ margin: ".3rem 0" }}>{message.content}</p>{message.referencedBlockIds?.length ? <small className="muted">依據段落：{message.referencedBlockIds.join("、")}</small> : null}</div>)}{loadingTutor && <p className="muted">導師正在思考…</p>}</div><div style={{ display: "flex", gap: ".4rem", marginTop: ".75rem" }}><input aria-label="問題" value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => event.key === "Enter" && askTutor()} placeholder="例如：為什麼要除以二？" style={{ minWidth: 0, flex: 1, padding: ".6rem", border: "1px solid #d7dfeb", borderRadius: 8 }} /><button className="button" disabled={loadingTutor} onClick={askTutor}>送出</button></div></aside>
    </div>
  </main>;
}

function Quiz({ quiz, onAnswer }: { quiz: Chapter["quizzes"][number]; onAnswer: (quizId: string, option: number) => void }) { const [answered, setAnswered] = useState<number | null>(null); return <section className="quiz"><b>小測驗：{quiz.question}</b>{quiz.options.map((option, index) => <button className="option" key={option} disabled={answered !== null} onClick={() => { setAnswered(index); onAnswer(quiz.id, index); }}>{option}</button>)}{answered !== null && <p className={answered === quiz.correctOptionIndex ? "" : "muted"}>{answered === quiz.correctOptionIndex ? "答對了！" : quiz.explanation}</p>}</section>; }
